# Generated by Django 4.2.2 on 2023-06-27 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('phone', models.IntegerField()),
                ('purchase_date', models.DateField(default=datetime.date)),
            ],
        ),
        migrations.CreateModel(
            name='producat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/')),
                ('name', models.CharField(max_length=100)),
                ('dis', models.TextField(max_length=500)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Vikas Sharma', max_length=50)),
                ('address', models.CharField(default='IFCO Chowk, Delhi', max_length=150)),
                ('phone', models.IntegerField(default='+91 8171415434')),
                ('date', models.DateField(default=datetime.date)),
            ],
        ),
    ]
