# Generated by Django 4.2.2 on 2023-06-28 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='producat',
            new_name='products',
        ),
    ]
