# Generated by Django 4.2.2 on 2023-06-28 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_rk_alter_seller_address_alter_seller_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='seller',
            new_name='service',
        ),
    ]
