# Generated by Django 4.2.2 on 2023-06-28 04:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_rename_seller_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='purchase_date',
            field=models.DateField(default=datetime.date(2023, 6, 28)),
        ),
        migrations.AlterField(
            model_name='service',
            name='date',
            field=models.DateField(default=datetime.date(2023, 6, 28)),
        ),
        migrations.AlterField(
            model_name='service',
            name='phone',
            field=models.IntegerField(default='+91 9121862212', max_length=20),
        ),
    ]
