# Generated by Django 4.2.2 on 2023-06-28 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_alter_buyer_purchase_date_alter_service_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='phone',
        ),
    ]
