# Generated by Django 4.2.2 on 2023-06-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_remove_service_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='phone',
            field=models.CharField(default='+91 9121862212', max_length=20),
        ),
    ]
