# Generated by Django 4.2.2 on 2023-06-28 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_service_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='service',
            new_name='seller',
        ),
    ]
