# Generated by Django 4.2.2 on 2023-06-28 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_alter_buyer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 28, 8, 40, 20, 715249, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='seller',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 28, 8, 40, 20, 715249, tzinfo=datetime.timezone.utc)),
        ),
    ]
