# Generated by Django 4.2.2 on 2023-06-28 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_alter_buyer_purchase_date_alter_seller_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 28, 8, 58, 48, 8469, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='seller',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 28, 8, 58, 48, 8469, tzinfo=datetime.timezone.utc)),
        ),
    ]
